version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
      - "3000:3000"
    
    volumes:
      - ./backend:/usr/src/app/backend
      - ./frontend:/usr/src/app/frontend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
